const tl = gsap.timeline({defaults: {stagger:1, yoyo:true} })
    .fromTo('.from', {delay: 0, scale:0, opacity:0}, {duration:2, scale: 1, opacity:1, ease: "back"}, 0)
    .fromTo('.ideasH1', {scale:3, opacity: 0}, {duration:2, scale:1, opacity: 1, ease: "back"}, 1)
    .fromTo('#ideas', {x:'0vw', zIndex: '2'}, {duration:2, x:'-100vw', zIndex: '2',  ease: "power"}, 3)
    .fromTo('#concepts', {opacity: 1}, {duration:0, opacity:1, ease:'Power0.easeNone'}, 2.5)
    .fromTo('.to', {delay: 0, scale:0, opacity:0}, {duration:2, scale: 1, opacity:1, ease: "back"}, 3.5)
    .fromTo('.h1-for-concepts', {scale:3, opacity: 0}, {duration:2, scale:1, opacity: 1, ease: "back"}, 4.5)
    .fromTo('#concepts', {x:'0vw', zIndex: '0'}, {duration:2, x:'-100vw', zIndex: '1',  ease: "power"}, 6.5)
    .fromTo('#products', {opacity: 1, zIndex: '-1'}, {duration:0, opacity:1, zIndex: '-1', ease:'Power0.easeNone'}, 6.5)
    .fromTo('.then', {delay: 0, y:'-100vh', opacity: 0}, {duration:2, y:'0vh', opacity:1, ease: "back"}, 7.5)
    .fromTo('.productsH1', {delay: 0, y:'100vh', opacity: 0}, {duration:2, y:'0vh', opacity:1, ease: "back"}, 9)
    .fromTo('#products', {x:'0vw', zIndex: '-1'}, {duration:2, x:'-100vw', zIndex: '-1',  ease: "power"}, 11)
    .fromTo('#market', {opacity: 1, zIndex: '-2'}, {duration:0, opacity:1, zIndex: '-2', ease:'Power0.easeNone'}, 7.5)
    .fromTo('.finally', {delay: 0, y:'-100vh', opacity: 0}, {duration:2, y:'0vh', opacity:1, ease: "back"}, 11.5)
    .fromTo('.flash-slide_market-h1', {delay: 0, y:'100vh', opacity: 0}, {duration:2, y:'0vh', opacity:1, ease: "back"}, 13)
    .fromTo('.flash-slide_market-left', {x:'0vw', zIndex: '-3'}, {duration:2, x:'-50vw', zIndex: '-3',  ease: "Power0.easeNone"}, 16)
    .fromTo('.marketRight', {x:'0vw', zIndex: '-3'}, {duration:2, x:'50vw', zIndex: '-3',  ease: "Power0.easeNone"}, 16)
    .fromTo('.flash-slide_market-h1', {delay: 0, x:'0vw', opacity: 1}, {duration:2, x:'-100vw', opacity:0, ease: "Power0.easeNone"}, 16)
    .fromTo('.finally', {delay: 0, x:'0vw', opacity: 1}, {duration:2, x:'100vw', opacity:0, ease: "Power0.easeNone"}, 16)
    .fromTo('.welcomeH1', {delay: 0, x:'100vw', opacity: 0}, {duration:3, x:'0vw', opacity: 1, ease: "Power0.easeNone"}, 17)
    .fromTo('.welcomeH1', {delay: 0, x:'0vw'}, {duration:3, x:'100vw', ease: "Power0.easeNone"}, 22)
    .fromTo('.welcome', {zIndex: '-99'}, {zIndex: '1', ease: "Power0.easeNone"}, 20)    
gsap.fromTo('#logo, .logo', {scale:0, opacity: 1, zIndex:999}, {duration:10, opacity:1, scale:1, zIndex:999, ease: 'back'}, 15.5)